window.struct_10 = {
	ver: 10,
	editorVer: "10",
	main: [
		"unknown_head", "int16",
		"sht_off_cnt", "int16",
		"判定点大小（未使用）", "float",
		"擦弹范围（未使用）", "float",
		"道具吸取范围（未使用）", "float",
		"高速直向移速", "float",
		"低速直向移速", "float",
		"高速斜向移速", "float",
		"低速斜向移速", "float",
		"option_pos", "option_pos",
		"sht_off", "sht_off",
		"sht_arr", "sht_arr"
	],
	option_pos: [
		"x", "float",
		"y", "float",
		"padding", "uint32" //always 0?
	],
	sht_off: [
		"offset", "uint32",
		"jank", "int32"
	],
	sht_arr: [
		"发射间隔", "byte",
		"发射延迟", "byte",
		"伤害", "int16",
		"偏移x", "float",
		"偏移y", "float",
		"判定a", "float",
		"判定b", "float",
		"角度", "float",
		"弹速", "float",
		"绑定子机", "byte",
		"unknown_sht_byte_0", "byte",
		"纹理ID", "int16",
		"击中纹理ID", "int16",
		"音效ID", "int16",
		"初始效果", "int32",
		"每帧效果", "int32",
		"渲染效果", "int32",
		"击中效果", "int32",
	],
	sht_off_type: "abs",
	option_pos_len: 0xF0,
	max_opt: 0x08,
	flags_len: 0x0,
	flag_size: 2,
	type: "maingame",
	forced_shtoffarr_len: false,
	f_uf_shooter_split: true
};
