window.struct_09 = {
	ver: 9,
	editorVer: "09",
	main: [
		"unknown_head", "int16",
		"sht_off_cnt", "int16",
		"unknown_pofv_0", "float", 
		"判定点大小（未使用）", "float",
		"擦弹范围（未使用）", "float",
		"道具吸取范围（未使用）", "float",
		"高速直向移速", "float",
		"低速直向移速", "float",
		"高速斜向移速", "float",
		"低速斜向移速", "float",
		"unknown_pofv_1", "float",
		"unknown_pofv_2", "float",
		"spellname_arr", "spellname_arr",
		"sht_off", "sht_off",
		"sht_arr", "sht_arr"
	],
	sht_off: [
		"offset", "uint32",
		"power", "uint32"
	],
	sht_arr: [
		"发射间隔", "byte",
		"发射延迟", "byte",
		"伤害", "int16",
		"偏移x", "float",
		"偏移y", "float",
		"判定a", "float",
		"判定b", "float",
		"角度", "float",
		"unknown_old_sht_0", "int16",
		"绑定子机", "byte",
		"unknown_old_sht_1", "byte",
		"unknown_old_sht_2", "int16",
		"纹理ID", "int16",
		"音效ID", "int16",
		"flags", "flags",
		"初始效果", "int32",
		"每帧效果", "int32",
		"渲染效果", "int32",
		"击中效果", "int32",
	],
	sht_off_type: "abs",
	option_pos_len: false, 
	max_opt: false, 
	flags_len: 0x0,
	flag_size: 2,
	type: "maingame",
	forced_shtoffarr_len: false,
	f_uf_shooter_split: false,
	spellname_arr_len: 0x10,
	spellname_len: 0x40
};
