window.struct_14 = {
	ver: 14,
	editorVer: "14",
	main: [
		"unknown_head", "int16",
		"sht_off_cnt", "int16",
		"判定点大小（未使用）", "float",
		"擦弹范围（未使用）", "float",
		"道具吸取范围（未使用）", "float",
		"高速直向移速", "float",
		"低速直向移速", "float",
		"高速斜向移速", "float",
		"低速斜向移速", "float",
		"最大power", "int16",
		"max_dmg_u", "int16",
		"SA_power_divisor", "int32",
		"max_dmg", "int32",
		"unknown_2", "int32",
		"unknown_3", "int32",
		"unknown_4", "int32",
		"unknown_5", "int32",
		"unknown_6", "int32",
		"option_pos", "option_pos",
		"sht_off", "sht_off",
		"sht_arr", "sht_arr"
	],
	option_pos: [
		"x", "float",
		"y", "float"
	],
	sht_off: [
		"offset", "uint32"
	],
	sht_arr: [
		"发射间隔", "byte",
		"发射延迟", "byte",
		"伤害", "int16",
		"偏移x", "float",
		"偏移y", "float",
		"判定a", "float",
		"判定b", "float",
		"角度", "float",
		"弹速", "float",
		"unknown_sht_int32", "int32",
		"绑定子机", "byte",
		"unknown_sht_byte_0", "byte",
		"纹理ID", "byte",
		"击中纹理ID", "byte",
		"音效ID", "int16",
		"unknown_sht_int16", "int16", // NOT rate2/delay2
		"初始效果", "int32",
		"每帧效果", "int32",
		"渲染效果", "int32",
		"击中效果", "int32",,
		"flags", "flags"
	],
	sht_off_type: "rel",
	option_pos_len: 0xA0,
	max_opt: 0x04,
	flags_len: 0x20,
	flag_size: 2,
	type: "maingame",
	forced_shtoffarr_len: 0x0A,
	f_uf_shooter_split: true
};
